[options]
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
admin_passwd = $pbkdf2-sha512$600000$kdI6Z4zRmrMWAoDQWmvN2Q$6gnD9Lh1Pvmsq7QUhdiHKz4EH571cs2AAampzSw.PH7EInUzsIBojSDZ70hPynJqHpzemyMJGCLDcOpkWBhLIQ

